# Generated by Django 2.2.6 on 2019-10-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archerysettings', '0006_burp_setting_db_burp_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='sonarqube_setting_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sonarqube_url', models.TextField(blank=True, null=True)),
                ('sonarqube_user', models.TextField(blank=True, null=True)),
                ('sonarqube_pwd', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
