# Generated by Django 2.2.6 on 2019-10-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archerysettings', '0008_auto_20191003_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openvas_setting_db',
            name='password',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='openvas_setting_db',
            name='user',
            field=models.TextField(blank=True, null=True),
        ),
    ]
