# Generated by Django 2.2.6 on 2019-10-03 18:25

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('archerysettings', '0010_auto_20191003_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openvas_setting_db',
            name='password',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=150, null=True)),
        ),
        migrations.AlterField(
            model_name='openvas_setting_db',
            name='user',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=150, null=True)),
        ),
    ]
