# Generated by Django 2.2.6 on 2019-10-03 19:22

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('archerysettings', '0011_auto_20191003_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sonarqube_setting_db',
            name='sonarqube_pwd',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, null=True)),
        ),
        migrations.AlterField(
            model_name='sonarqube_setting_db',
            name='sonarqube_user',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, null=True)),
        ),
    ]
